config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'
  # root "articles#index"
  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end
  resources :reviews, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  CATEGORY = ["chinese", "italian", "japanese", "french", "belgian"]

  validates :name, :address, :category, presence: true
  validates :category, inclusion: { in: CATEGORY }

  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, numericality: { only_integer: true }
  validates :rating, inclusion: { in: 0..5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[show edit update destroy]

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    # @review = Review.new
  end

  # def edit

  # end

  # def update

  # end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category, :phone_number)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  #   @review.restaurant = @restaurant
  #   if @review.save
  #     redirect_to restaurant_path(@restaurant)
  #   else
  #     render "restaurants/show", status: :unprocessable_entity
  #   end
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@review.restaurant), status: :see_other
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/index.html.erb
<div class="container mt-3">
  <h1>Restaurants</h1>

  <ul>
    <% @restaurants.each do |restaurant| %>
      <%= link_to restaurant_path(restaurant), class: "text-decoration-none link-primary d-block" do %>
        <%= restaurant.name %>
      <% end %>
    <% end %>
  </ul>

  <div class="col-4">
    <%= link_to 'Add New Restaurant', new_restaurant_path, class: 'btn btn-primary' %>
  </div>

</div>

app/views/restaurants/new.html.erb
<div class="row mt-3">

  <h1>Add your new restaurant</h1>

  <%= simple_form_for(@restaurant) do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :category, collection: Restaurant::CATEGORY %>
    <%= f.submit class: 'btn btn-danger', value: "Add Restaurant"%>
  <% end %>

  <div class="col-2">
    <%= link_to "Back to Homepage", restaurants_path, class: 'btn btn-primary mt-3' %>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="row mt-3">

  <h1><%= @restaurant.name %></h1>
  <p class="mt-3"><strong>Address: </strong><%= @restaurant.address %></p>
  <p><strong>Phone Number: </strong><%= @restaurant.phone_number %></p>
  <p><strong>Type of Food: </strong><%= @restaurant.category.capitalize %></p>

  <%# <div class="">
  <label for="reviewing">Write your review about "<%= @restaurant.name %>
  <%# <input type="text" id="reviewing" class="col-4">
  <input type="submit" id="reviewing">
  <%= link_to "Submit", restaurants_path, class: 'btn btn-primary mt-3' %>
  <%# </div> %>

  <p><strong>Reviews:</strong></p>
  <p><%= link_to "Add Review", new_restaurant_review_path(@restaurant), class: 'btn btn-danger' %></p>
  <ul class="list-group">
    <% @restaurant.reviews.each do |review| %>
      <li class="list-group-item">
        <%= review.content %>
        <%= link_to review_path(review), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
          <i class="fa-solid fa-trash opacity-75 link-secondary"></i>
        <% end %>
      </li>
    <% end %>
  </ul>
  <br>

  <div class="col-2">
    <%= link_to "Back to Homepage", restaurants_path, class: 'btn btn-primary mt-3' %>
  </div>

</div>

app/views/reviews/new.html.erb
<div class="container mt-3">
  <h1>New review</h1>
  <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :rating %>
    <%= f.input :content %>
    <%= f.submit "Submit Review", class: "btn btn-danger" %>
  <% end %>

  <div class="col-4">
    <%= link_to restaurant_path(@restaurant), class: 'btn btn-primary mt-3' do %>
      Back to <%= @restaurant.name %>
    <% end %>
  </div>
</div>